FROM almalinux:9
ENV course="Devops with AWS"
    engineer="Dakshina Murthy Nallapati"
    duraion="120HRS"
ARG USERNAME=Dakshina Murthy Nallapati
RUN echo "Hello User: ${USERNAME}"
CMD ["sleep", "180"]